### ISSUE TITLE
Broken links in readme

### ISSUE THREAD

**Issue by lolmaus** [Toadstool-Stipe/toadstool#16]
Links in the readme point at an obsolete project location.

I wanted to commit a fix but then i saw you using goo.gl, probably for counting hits. I wish you revert to pure links though: being unable to see where you're going to find yourself is disturbing.

**Comment by lolmaus** [comment]
@blackfalcon, why have you closed this? The issue still stands.

**Comment by blackfalcon** [comment]
project is no longer being maintained.

**Comment by lolmaus** [comment]
Why not keep unresolved issues open? 🤷‍♂
